addon/controllers/fd-appstruct-list-form.js, addon/routes/fd-appstruct-list-form.js, addon/transforms/containers-tree.js
Complete serialize/unserialize containersStr field
record.save():
Error<(unknown mixin):ember1990> :-(
=> Feature 151767 app structure form

addon/locales/ru/models/fd-dev-class.js, addon/mixins/regenerated/models/fd-dev-class.js, addon/mixins/regenerated/models/fd-dev-view.js, addon/mixins/regenerated/serializers/fd-dev-class-offline.js, addon/mixins/regenerated/serializers/fd-dev-class.js
Fix relationships and projections for `fd-dev-class` model.
=> Fix `fd-dev-class`

addon/locales/en/models/fd-dev-class.js, vendor/flexberry/models/fd-dev-class.json
=> Fix unfixed `devViews` relationship

addon/controllers/fd-stage-edit-form.js, addon/locales/en/forms/fd-stage-edit-form.js, addon/locales/ru/forms/fd-stage-edit-form.js, app/templates/fd-stage-edit-form.hbs, package.json
=> Update template stage

addon/transforms/containers-tree.js
TFS #156671
"for ... of" is incompatible with IE.
=> Fix work in ie

addon/controllers/fd-stage-edit-form.js, addon/routes/fd-stage-edit-form.js, app/templates/fd-stage-edit-form.hbs, tests/dummy/config/environment.js
=> Feature 157098 save and read modulesettings

addon/controllers/fd-appstruct-list-form.js, package.json
TFS #157391
Merge this after pull request https://github.com/Flexberry/ember-flexberry/pull/506
=> Fix remove, upRight and downRight for RightTree

addon/controllers/fd-stage-edit-form.js, addon/routes/fd-stage-edit-form.js
TFS #157098 
Сhanges on backend: changeset 152680
=> Action save modulesettings

addon/components/fd-visual-diagram.js
TFS: [#163659](http://dis-tfs:8080/Common/CASEBERRY/_workitems/edit/163659).
=> Show collapsed folded classes on diagrams

addon/controllers/fd-class-edit-form.js, app/templates/fd-class-edit-form.hbs
=> Add dropdownIsSearch property to business server lookup, lookup filter

addon/components/fd-editform-control.js, addon/components/fd-editform-row.js, app/components/fd-editform-control.js, app/components/fd-editform-row.js, app/templates/components/fd-editform-control.hbs, app/templates/components/fd-editform-row.hbs, app/templates/fd-editform-constructor.hbs, tests/integration/components/fd-editform-control-test.js, tests/integration/components/fd-editform-row-test.js
TFS: [#163422](http://dis-tfs:8080/Common/CASEBERRY/_workitems/edit/163422).
=> Render editform constructor

addon/mixins/regenerated/models/fd-dev-view.js, addon/objects/fd-view-attributes-datail.js, addon/objects/fd-view-attributes-master.js, addon/objects/fd-view-attributes-property.js, addon/transforms/fd-definition.js
=> Add object model and update transforms view

addon/components/fd-editform-row.js, addon/controllers/fd-editform-constructor.js, addon/locales/en/forms/fd-editform-constructor.js, addon/locales/ru/forms/fd-editform-constructor.js, addon/routes/fd-editform-constructor/form-config-panel.js, app/routes/fd-editform-constructor/form-config-panel.js, app/templates/components/fd-editform-control.hbs, app/templates/components/fd-editform-row.hbs, app/templates/fd-editform-constructor.hbs, app/templates/fd-editform-constructor/form-config-panel.hbs, tests/dummy/app/router.js, tests/dummy/app/templates/application.hbs, tests/integration/components/fd-editform-control-test.js, tests/integration/components/fd-editform-row-test.js, tests/unit/routes/fd-editform-constructor/form-config-panel-test.js
TFS: [#163422](http://dis-tfs:8080/Common/CASEBERRY/_workitems/edit/163422).
=> Add sidebar in editform-constructor

addon/components/fd-editform-row.js, addon/controllers/fd-editform-constructor.js, app/templates/components/fd-editform-control.hbs, app/templates/components/fd-editform-row.hbs, app/templates/fd-editform-constructor.hbs
TFS: Part of [#165490](http://dis-tfs:8080/Common/CASEBERRY/_workitems/edit/165490).
=> Drag and drop for rows

addon/components/fd-editform-control.js, addon/components/fd-editform-row.js, addon/controllers/fd-editform-constructor.js, addon/mixins/fd-draggable-control.js, addon/styles/addon.less, app/templates/components/fd-editform-control.hbs, app/templates/components/fd-editform-row.hbs, app/templates/fd-editform-constructor.hbs, tests/integration/components/fd-editform-control-test.js, tests/integration/components/fd-editform-row-test.js, tests/unit/mixins/fd-draggable-control-test.js
TFS: Part of [#165490](http://dis-tfs:8080/Common/CASEBERRY/_workitems/edit/165490).
=> Drag and drop for controls

addon/controllers/fd-appstruct-form.js, app/templates/fd-appstruct-form.hbs, tests/dummy/app/router.js
=> Update appstruct form

addon/controllers/fd-appstruct-form.js, addon/transforms/containers-tree.js, tests/unit/transforms/containers-tree-test.js
=> Add save and move

addon/controllers/fd-appstruct-form.js, addon/objects/fd-appstruct-tree.js, addon/routes/fd-appstruct-form.js, addon/transforms/containers-tree.js, app/templates/fd-appstruct-form.hbs, tests/unit/transforms/containers-tree-test.js
=> Feature 163633 fix transforms

CHANGELOG.md, addon/components/fd-editform-control.js, addon/components/fd-editform-row.js, addon/controllers/fd-editform-constructor.js, addon/styles/components/fd-editform-control.less, addon/styles/components/fd-editform-row.less, app/templates/components/fd-editform-control.hbs, app/templates/components/fd-editform-row.hbs, app/templates/fd-editform-constructor.hbs, tests/integration/components/fd-editform-control-test.js, tests/integration/components/fd-editform-row-test.js
=> Improve selectable on edit form constructor

CHANGELOG.md, addon/components/fd-editform-control.js, addon/controllers/fd-editform-constructor.js, addon/locales/en/forms/fd-editform-constructor.js, addon/locales/ru/forms/fd-editform-constructor.js, addon/objects/fd-editform-tabgroup.js, app/templates/fd-editform-constructor.hbs
=> Improved addition on the edit form constructor

CHANGELOG.md, addon/controllers/fd-view-edit-form.js, addon/locales/en/forms/fd-view-edit-form.js, addon/locales/ru/forms/fd-view-edit-form.js, addon/utils/fd-get-view-tree-node.js, app/templates/fd-view-edit-form.hbs
=> Fix view edit form

CHANGELOG.md, addon/controllers/fd-editform-constructor.js, addon/locales/en/forms/fd-editform-constructor.js, addon/locales/ru/forms/fd-editform-constructor.js, app/templates/fd-editform-constructor.hbs, tests/unit/controllers/fd-editform-constructor-test.js
=> Remove and move controls on the edit form constructor

addon/components/fd-visual-edit-control-tree.js, addon/locales/en/components/fd-visual-edit-control-tree.js, addon/locales/ru/components/fd-visual-edit-control-tree.js, addon/objects/fd-editform-control.js, addon/templates/components/fd-visual-edit-control-tree.hbs
=> Fix component for editform-constructor

addon/components/fd-editform-control.js, addon/controllers/fd-editform-constructor.js, addon/locales/en/components/fd-visual-edit-control-tree.js, addon/locales/ru/components/fd-visual-edit-control-tree.js, addon/routes/fd-editform-constructor.js, addon/templates/components/fd-visual-edit-control-tree.hbs
=> Add visible in control

addon/controllers/fd-editform-constructor.js, addon/locales/ru/forms/fd-editform-constructor.js, addon/objects/fd-editform-control.js, app/templates/fd-editform-constructor.hbs
=> Restore DnD functionality

addon/components/fd-visual-edit-control-tree.js, addon/controllers/fd-editform-constructor.js, addon/templates/components/fd-visual-edit-control-tree.hbs
=> Change not null associations in the edit form constructor

addon/controllers/fd-appstruct-form.js
=> Fix save appstruct form

addon/components/fd-visual-edit-control-tree.js, addon/controllers/fd-editform-constructor.js, addon/routes/fd-editform-constructor.js, addon/templates/components/fd-visual-edit-control-tree.hbs
=> Feature 167106 fix name in controls

app/templates/fd-appstruct-form.hbs
=> Fix delete modal

addon/controllers/fd-editform-constructor.js, addon/locales/en/forms/fd-editform-constructor.js, addon/locales/ru/forms/fd-editform-constructor.js, app/templates/fd-editform-constructor.hbs
=> Selecting an added control in the edit form constructor

addon/controllers/fd-editform-constructor.js, addon/utils/fd-attributes-for-tree.js
=> fix create path

addon/controllers/fd-appstruct-form.js, addon/routes/fd-editform-constructor.js
=> Fix update view definition

addon/locales/en/forms/fd-appstruct-form.js, addon/locales/ru/forms/fd-appstruct-form.js, addon/routes/fd-appstruct-form.js, app/templates/fd-appstruct-form.hbs
=> Add on tab app settings

addon/routes/fd-appstruct-form.js, addon/routes/fd-association-list-form.js, addon/routes/fd-class-list-form.js, addon/routes/fd-inheritance-list-form.js, addon/routes/fd-view-list-form.js, tests/dummy/app/controllers/application.js, tests/dummy/app/locales/en/translations.js, tests/dummy/app/locales/ru/translations.js, tests/dummy/app/styles/app.less, tests/dummy/app/templates/application.hbs
Reverts Flexberry/ember-flexberry-designer#148
=> Revert "Fix association route"

addon/controllers/fd-appstruct-form.js, addon/controllers/fd-listform-constructor.js, addon/routes/fd-listform-constructor.js, addon/utils/fd-create-form-properties.js, app/templates/fd-listform-constructor.hbs
=> Fix create list form

addon/controllers/fd-generation-process-form.js, addon/locales/en/forms/fd-generation-process-form.js, addon/locales/ru/forms/fd-generation-process-form.js, addon/routes/fd-generation-process-form.js, app/templates/fd-generation-process-form.hbs
=> Add loading in generation

CHANGELOG.md, addon/controllers/fd-appstruct-form.js, addon/transforms/containers-tree.js, tests/unit/transforms/containers-tree-test.js
=> Adding links into desktop root

addon/utils/fd-attributes-for-tree.js, app/templates/fd-listform-constructor.hbs
=> Fix persing propertyname

app/templates/fd-generation-list-form.hbs, app/templates/fd-generation-process-form.hbs
* Hide the «Add» button in the generation list
* Disable the «Generate» button for running generation
=> Fix generation forms

addon/controllers/fd-listform-constructor.js, app/templates/fd-listform-constructor.hbs
=> A set of fixes for the list form constructor

addon/controllers/fd-view-edit-form.js, app/templates/fd-view-edit-form.hbs, tests/dummy/app/templates/loading.hbs
=> Fix save and close in the view edit form

addon/controllers/fd-stage-edit-form.js
=> Fixed error when saving a new stage

addon/components/fd-visual-edit-control-tree.js
=> Add attribute highlighting in the tree for form constructors

addon/components/fd-editform-control.js, addon/components/fd-visual-edit-control-tree.js, app/templates/components/fd-editform-control.hbs, app/templates/components/fd-lookup.hbs
=> A set of fixes for the edit form constructor

tests/dummy/app/routes/collaboration-diagram-primitives-demo.js
There was a link to the remote utility
=> Fix merge error

addon/components/fd-uml-diagram.js, addon/controllers/fd-diagram-edit-form.js, addon/locales/en/forms/fd-diagram-edit-form.js, addon/locales/ru/forms/fd-diagram-edit-form.js, addon/mixins/fd-creating-diagram-elements-controller.js, addon/objects/uml-primitives/fd-uml-association.js, addon/objects/uml-primitives/fd-uml-class.js, addon/objects/uml-primitives/fd-uml-primitive.js, app/templates/fd-diagram-edit-form.hbs
=> Add metods for creating joint js elements on diagrams

addon/mixins/actions-for-primitives/fd-actions-for-cad-primitives.js, addon/routes/fd-view-edit-form.js
=> Fix error of moving and removing attributes in the view edit form

CHANGELOG.md, addon/objects/uml-primitives/fd-uml-active-object.js, addon/objects/uml-primitives/fd-uml-baseobject.js, addon/objects/uml-primitives/fd-uml-class.js, addon/objects/uml-primitives/fd-uml-instance.js, addon/objects/uml-primitives/fd-uml-multi-object.js, addon/objects/uml-primitives/fd-uml-naryassociation.js, addon/objects/uml-primitives/fd-uml-package.js, addon/objects/uml-primitives/fd-uml-template-class.js, addon/styles/fd-uml-diagram.less
=> Update cad elements

CHANGELOG.md, addon/objects/uml-primitives/fd-uml-baseobject.js, addon/objects/uml-primitives/fd-uml-package.js, addon/styles/fd-uml-diagram.less
=> Fix autoresize of uml package

addon/mixins/actions-for-primitives/fd-actions-for-cad-primitives.js, addon/objects/uml-primitives/fd-uml-multi-object.js, addon/objects/uml-primitives/fd-uml-template-class.js, addon/styles/fd-uml-diagram.less
=> Fix autoresize of uml template class

addon/objects/uml-primitives/fd-uml-naryassociation.js
=> Fix autoresize of uml naryassociation

CHANGELOG.md, addon/controllers/fd-editform-constructor.js, app/templates/fd-editform-constructor.hbs, tests/unit/controllers/fd-editform-constructor-test.js
=> Add moving one control in row as whole row

CHANGELOG.md, addon/styles/fd-uml-diagram.less
=> Fix 276 new diagram canvas size

addon/components/fd-search-input.js, addon/locales/en/forms/fd-application-model.js, addon/locales/en/translations.js, addon/locales/ru/forms/fd-application-model.js, addon/styles/addon.less, addon/styles/default/collections/form.variables, addon/styles/default/elements/input.variables, addon/templates/components/fd-search-input.hbs, app/components/fd-search-input.js, app/templates/fd-application-model.hbs, tests/integration/components/fd-search-input-test.js
=> fix: fd-list markup

CHANGELOG.md, addon/locales/ru/translations.js, addon/styles/addon.less, tests/dummy/app/controllers/application.js, tests/dummy/app/templates/application.hbs
=> Feature current project view

addon/components/fd-class-list-items.js, addon/components/fd-list-item.js, addon/components/fd-sheet.js, addon/controllers/fd-application-model.js, addon/locales/en/forms/fd-application-model.js, addon/locales/ru/forms/fd-application-model.js, addon/mixins/fd-sheet-mixin.js, addon/routes/fd-application-model.js, addon/templates/components/fd-class-list-items.hbs, addon/templates/components/fd-list-item.hbs, app/components/fd-class-list-items.js, app/templates/fd-application-model.hbs
=> update form app model

addon/styles/addon.less, addon/styles/default/elements/button.overrides, addon/styles/default/globals/site.variables, addon/styles/default/views/card.overrides, addon/styles/default/views/card.variables, app/templates/fd-all-projects.hbs, app/templates/fd-all-projects/index.hbs
=> feat: All projects page style

addon/components/fd-attribute-table.js, addon/components/fd-editing-panels/fd-enumeration-editing-panel.js, addon/components/fd-editing-panels/fd-implementation-editing-panel.js, addon/components/fd-editing-panels/fd-interface-editing-panel.js, addon/controllers/fd-application-model.js, addon/locales/en/components/fd-attribute-table.js, addon/locales/en/components/fd-enumeration-editing-panel.js, addon/locales/en/components/fd-implementation-editing-panel.js, addon/locales/en/components/fd-interface-editing-panel.js, addon/locales/ru/components/fd-attribute-table.js, addon/locales/ru/components/fd-enumeration-editing-panel.js, addon/locales/ru/components/fd-implementation-editing-panel.js, addon/locales/ru/components/fd-interface-editing-panel.js, addon/mixins/fd-editing-panels/fd-update-attribute-value.js, addon/mixins/fd-editing-panels/fd-update-bs-value.js, addon/mixins/fd-editing-panels/fd-update-method-value.js, addon/mixins/fd-editing-panels/fd-update-view-value.js, addon/templates/components/fd-attribute-table.hbs, addon/templates/components/fd-editing-panels/fd-enumeration-editing-panel.hbs, addon/templates/components/fd-editing-panels/fd-implementation-editing-panel.hbs, addon/templates/components/fd-editing-panels/fd-interface-editing-panel.hbs
=> Update edit panels

addon/objects/uml-primitives/fd-uml-link.js, tests/dummy/config/environment.js
=> Change points order

addon/transforms/fd-primitives-json-string.js
While the method unserialize()  is made ...
The implementation of the method serialize() has been postponed until the record is implemented
Resolve #352
=> Feature 352 multo connectors links
